CREATE TABLE CONFIG_PARAM (
  CONFIG_ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
  CONFIG_KEY VARCHAR(100) NOT NULL,
  CONFIG_VALUE VARCHAR(500) NOT NULL,
  CONFIG_DESCRIPTION VARCHAR(500) NULL,
  constraint CONFIG_KEY_UN unique (CONFIG_KEY)
 );